language: generic
sudo: required
services: 
    - docker
    
before_install:
    - docker build -t nonameforpirate2/docker-react2 -f Dockerfile.dev . 
    
script:
    - docker run nonameforpirate2/docker-react2 npm run test -- --coverage